apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservation
  name: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reservation
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/swift-radar-404502/reservation/production:latest
          name: reservation
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: PORT
              value: "3004"
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: "3002"
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENTS_PORT
              value: "3001"
          ports:
            - containerPort: 3004
