apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservation
  name: reservation
spec:
  ports:
    - name: "tcp"
      port: 3004
      protocol: TCP
      targetPort: 3004
  selector:
    app: reservation
  type: NodePort
